Various changes
EficodeEntDemo/pluto pull request #121
Opened 2021-11-02 10:21 UTC by CptPicard

* Make use of authorized user inside code
* Change repository creation endpoint not to take url from frontend
* Pass github auth token from frontend

2021-11-02 11:47 UTC, romuaa commented on backend/endpoints/app/api/__init__.py
> +app.config["USE_LOCAL_LAMBDA_CALLS"] = True if os.environ.get("USE_LOCAL_LAMBDA_CALLS") else False
I added helper for this in main. This could be just 
app.config["USE_LOCAL_LAMBDA_CALLS"] = get_boolean(os.environ.get("USE_LOCAL_LAMBDA_CALLS", False))

2021-11-02 12:02 UTC, romuaa requested changes
Few minor things that I think would make it cleaner. Look at the comments.

2021-11-02 12:02 UTC, romuaa commented on backend/endpoints/app/utils/common.py
> +def build_local_lambda_payload(data):
Is there a need for awsgi in the git lambda really? We could just post plain json to it without the http wsgi wrapping? It does not need to be exposed through the API Gateway as it is always only called by the api lambda?

2021-11-02 12:18 UTC, romuaa commented on backend/endpoints/app/services/project_service.py
> +        user_link = info.context['pluto_user'].user_link[0]  # Pretty ugly here because of db structure
But you should know the project you're dealing with and be able to implement a service method that executes appropriate dao method that does db query based on the user_account and project?

2021-11-02 12:58 UTC, mikkilevon commented on backend/endpoints/app/schema.graphql
> +    createRepository(name: String!, description: String, github_auth_token: String!): RepositoryResult!
doesn't createRepository also do the pushing of the template code?

2021-11-02 13:56 UTC, CptPicard commented on backend/endpoints/app/utils/common.py
> +def build_local_lambda_payload(data):
The git-lambda uses pluto_git#handle_template_service_call as the entrypoint. There is no AWSGI involved and yes it is just plain json that gets posted (or an AWS "event")

2021-11-02 14:05 UTC, romuaa commented on backend/endpoints/app/utils/common.py
> +def build_local_lambda_payload(data):
So where comes the need for 
{"path": "/api",
            "httpMethod": "POST",
            "queryStringParameters": "",
            "headers": {
                "content-type": "application/json"
                },
                
                why not just json.dumps(data) ?

2021-11-03 07:14 UTC, CptPicard commented on backend/endpoints/app/utils/common.py
> +def build_local_lambda_payload(data):
Ah. It's unused code. Removed.

2021-11-03 07:17 UTC, CptPicard commented on backend/endpoints/app/schema.graphql
> +    createRepository(name: String!, description: String, github_auth_token: String!): RepositoryResult!
No. They're two separate endpoints.

2021-11-03 11:15 UTC, romuaa requested changes

2021-11-03 11:15 UTC, romuaa commented on backend/endpoints/requirements_dev.txt
>  gitpython
boto3 missing from the dev dependencies?

2021-11-05 06:27 UTC, mikkilevon commented on backend/endpoints/app/schema.graphql
> +    createRepository(name: String!, description: String, github_auth_token: String!): RepositoryResult!
Is there a reason why this should be this way? (Thinking in frontend it's just 1 more query that can go wrong)

2021-11-05 06:29 UTC, mikkilevon commented on backend/endpoints/app/schema.graphql
> +    createRepository(name: String!, description: String, github_auth_token: String!): RepositoryResult!
Because I would maybe first push the template code and only then change the settings. This is so that you actually can push the code to main branch without any PRs

2021-11-08 11:34 UTC, romuaa approved these changes

2021-11-08 11:36 UTC, merged