Refine error handling
EficodeEntDemo/pluto pull request #184
Opened 2021-11-16 14:26 UTC by romuaa

2021-11-17 09:49 UTC, CptPicard requested changes

2021-11-17 09:49 UTC, CptPicard commented on backend/endpoints/app/services/project_service.py
> +    raise ServiceException("foobarfoo")
🤔 ❓

2021-11-17 09:49 UTC, CptPicard commented on backend/endpoints/app/services/project_service.py
> +        raise ServiceException("Bad Request")
These can be combined... except (NoResultFound, IntegrityError) as e

2021-11-22 13:38 UTC, mikkilevon approved these changes

2021-11-22 13:45 UTC, CptPicard approved these changes

2021-11-22 13:49 UTC, merged