Feature/dockerised lambdas
EficodeEntDemo/pluto pull request #56
Opened 2021-09-28 04:31 UTC by romuaa

2021-09-28 05:59 UTC, mikkilevon commented on backend/projects/README.md
> +```curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'```
BTW what is the /2015-03-31/ part of the URL?

2021-09-28 06:07 UTC, romuaa commented on backend/projects/README.md
> +```curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'```
No idea why the path is like that. Another date did not work.
https://docs.aws.amazon.com/lambda/latest/dg/images-test.html

2021-09-28 07:14 UTC, adamchabin submitted a review, later dismissed

2021-10-01 09:14 UTC, mikkilevon requested changes

2021-10-01 09:14 UTC, mikkilevon commented on backend/endpoints/log.txt
> +#1 [endpoints_dbmigration internal] load build definition from Dockerfile_migrations
I guess should be deleted?

2021-10-01 09:20 UTC, CptPicard approved these changes

2021-10-01 09:32 UTC, romuaa commented on backend/endpoints/log.txt
> +#1 [endpoints_dbmigration internal] load build definition from Dockerfile_migrations
I think it was already. Will do.

2021-10-01 09:34 UTC, mikkilevon approved these changes

2021-10-01 09:44 UTC, CptPicard approved these changes

2021-10-01 09:49 UTC, merged